AllCops:
  Include:
    - Guardfile
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['context', 'describe', 'feature', 'guard']

Metrics/AbcSize:
  Max: 39

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/Documentation:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/NestedParenthesizedCalls:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%i': '()'
    '%r': '{}'
    '%w': '()'

Style/RescueModifier:
  Enabled: false
