AllCops:
  Include:
    - Guardfile
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Max: 39

Metrics/BlockLength:
  ExcludedMethods: ['context', 'describe', 'feature', 'guard', 'included']

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 50

Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/Documentation:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/NestedParenthesizedCalls:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%i': '()'
    '%r': '{}'
    '%w': '()'

Style/RescueModifier:
  Enabled: false
