default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['POSTGRESQL_ADDRESS'] %>
  database: <%= ENV['POSTGRESQL_DATABASE'] %>
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  port: <%= ENV.fetch('POSTGRESQL_PORT', 5432) %>

production: &production
  <<: *default

production_swap: &production
  <<: *default

staging:
  <<: *production

qa:
  <<: *production

development:
  <<: *default

engageny:
  <<: *default
  database: <%= ENV['ENGAGENY_DATABASE'] %>

test:
  <<: *default

integration:
  <<: *default
