default:
  header: true
  name_date: true
  margin:
    top: 8.46
    right: 8.46
    bottom: 15
    left: 8.46
  orientation: portrait
  padding:
    right: 29px
    left: 29px
answer-lines:
  subtitle:
    classroom: Classroom Materials
    student: Student Handout
    teacher: Answer Key
icons:
  subtitle:
    classroom: Classroom Materials
    student: Student Handout
    teacher: Answer Key
family-letter:
  header: false
  subtitle:
    student: Student Handout
  title: Family Letter
first-then:
  subtitle:
    classroom: Classroom Materials
    student: Student Handout
    teacher: Answer Key
recommended-books:
  header: false
  subtitle:
    student: Student Handout
  title: Recommended Books
pdf:
  subtitle:
    pdf: Classroom Materials
somebody-wanted-but-so-then:
  subtitle:
    classroom: Classroom Materials
    student: Student Handout
    teacher: Answer Key
story-map:
  subtitle:
    classroom: Classroom Materials
    student: Student Handout
    teacher: Answer Key
student-worksheet:
  subtitle:
    classroom: Classroom Materials
    student: Student Handout
    teacher: Answer Key
sw-template-l:
  orientation: landscape
  subtitle:
    classroom: Classroom Materials
    student: Student Handout
    teacher: Answer Key
sw-template-p:
  subtitle:
    classroom: Classroom Materials
    student: Student Handout
    teacher: Answer Key
venn-diagram:
  subtitle:
    classroom: Classroom Materials
    student: Student Handout
    teacher: Answer Key
vocabulary-chart:
  header: false
  subtitle:
    classroom: Classroom Materials
  title: Vocabulary Chart
writing-and-drawing:
  subtitle:
    classroom: Classroom Materials
    student: Student Handout
    teacher: Answer Key
ic-template-l:
  name_date: false
  orientation: landscape
  subtitle:
    classroom: Classroom Materials
    student: Student Handout
    teacher: Answer Key
ic-template-p:
  name_date: false
  subtitle:
    classroom: Classroom Materials
    student: Student Handout
    teacher: Answer Key
