activity-metadata-type:
  stop_tags:
    - ActivityMetadataSectionTag
    - ActivityMetadataTypeTag
    - MaterialsTag
  priority_descriptions:
    - 'This part of the lesson is tightly connected to the lesson objective; avoid skipping this.'
    - 'This part of the lesson is less tightly connected to the lesson objective and can be skipped if running short on time. It might be designed as an extension or to ensure maintenance of prior skills.'
    - 'This part of the lesson is not connected to the lesson objective and can be skipped if running short on time. It might be designed in anticipation of upcoming learning.'
pv:
  hundreds:
    column_count: 1
    row_count: 3
    text_header: 'Unlabeled Hundreds Place Value Chart Template'
    text_footer: 'unlabeled hundreds place value chart'
  millions:
    column_count: 2
    row_count: 7
    text_footer: 'unlabeled millions place value chart'
    text_header: 'Unlabeled Millions Place Value Chart Template'
  thousands:
    column_count: 1
    row_count: 4
    text_footer: 'unlabeled thousands place value chart'
    text_header: 'Unlabeled Thousands Place Value Chart Template'
  hundred-thousands:
    column_count: 2
    column_width:
      - 10%
      - 85%
    row_count: 6
    text_footer: 'unlabeled hundred thousands place value chart'
    text_header: 'Unlabeled Hundred Thousands Place Value Chart Template'
section:
  stop_tags:
    - Ela6BreakTag
    - GroupTag
    - SectionTag
materials:
  stop_tags:
    - ActivityMetadataSectionTag
    - ActivityMetadataTypeTag
rubric:
  stop_tags:
    - AssessTag
    - EtTag
    - Ela6BreakTag
    - GroupTag
    - JsTag
    - KeyTag
    - PhotoTag
    - RubricTag
    - SectionTag
    - ShTag
    - ThTag
js:
  stop_tags:
    - AssessTag
    - EtTag
    - Ela6BreakTag
    - GroupTag
    - JsTag
    - KeyTag
    - PhotoTag
    - RubricTag
    - SectionTag
    - ShTag
    - ThTag
et:
  stop_tags:
    - AssessTag
    - EtTag
    - Ela6BreakTag
    - GroupTag
    - JsTag
    - KeyTag
    - PhotoTag
    - RubricTag
    - SectionTag
    - ShTag
    - ThTag
photo:
  stop_tags:
    - AssessTag
    - EtTag
    - Ela6BreakTag
    - GroupTag
    - JsTag
    - KeyTag
    - PhotoTag
    - RubricTag
    - SectionTag
    - ShTag
    - ThTag
assess:
  stop_tags:
    - AssessTag
    - EtTag
    - Ela6BreakTag
    - GroupTag
    - JsTag
    - KeyTag
    - PhotoTag
    - RubricTag
    - SectionTag
    - ShTag
    - ThTag
sh:
  stop_tags:
    - AssessTag
    - EtTag
    - Ela6BreakTag
    - GroupTag
    - JsTag
    - KeyTag
    - PhotoTag
    - RubricTag
    - SectionTag
    - ShTag
    - ThTag
key:
  stop_tags:
    - AssessTag
    - EtTag
    - Ela6BreakTag
    - GroupTag
    - JsTag
    - KeyTag
    - PhotoTag
    - RubricTag
    - SectionTag
    - ShTag
    - ThTag
th:
  stop_tags:
    - AssessTag
    - EtTag
    - Ela6BreakTag
    - GroupTag
    - JsTag
    - KeyTag
    - PhotoTag
    - RubricTag
    - SectionTag
    - ShTag
    - ThTag
